uploads = []

[[generated]]
id = "90XuTUgW0Sj0sbUgNvrLg"
uri = "file://artifacts/provision-civils/assets/images/icon.png"
type = "image"
title = "provision-civils-app-icon"

[[outputs]]
id = "VsSnC2Ku6eKCiEqzWYO3A"
uri = "file://provision-civils-apk.tar.gz"
type = "unspecified"
title = "Provision Civils APK (Android)"

[[outputs]]
id = "Bcn2X90elH8sDxIe59oOP"
uri = "file://provision-civils.zip"
type = "unspecified"
title = "Provision Civils APK — extract and install on Android"
