import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import dashboardRouter from "./dashboard.js";
import jobsRouter from "./jobs.js";
import clientsRouter from "./clients.js";
import expensesRouter from "./expenses.js";
import employeesRouter from "./employees.js";
import invoicesRouter from "./invoices.js";
import notificationsRouter from "./notifications.js";
import pdfRouter from "./pdf.js";
import downloadRouter from "./download.js";
import labourRouter from "./labour.js";
import leaveRouter from "./leave.js";
import payrollRouter from "./payroll.js";
import costingRouter from "./costing.js";
import versionRouter from "./version.js";
import teamsRouter from "./teams.js";
import messagesRouter from "./messages.js";
import announcementsRouter from "./announcements.js";
import auditRouter from "./audit.js";
import backupsRouter from "./backups.js";
import settingsRouter from "./settings.js";
import systemRouter from "./system.js";
import crashRouter from "./crash.js";
import activityRouter from "./activity.js";
import recycleRouter from "./recycle.js";

const router: IRouter = Router();

router.use(versionRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(jobsRouter);
router.use(clientsRouter);
router.use(expensesRouter);
router.use(employeesRouter);
router.use(invoicesRouter);
router.use(notificationsRouter);
router.use(pdfRouter);
router.use(downloadRouter);
router.use(labourRouter);
router.use(leaveRouter);
router.use(payrollRouter);
router.use(costingRouter);
router.use(teamsRouter);
router.use(messagesRouter);
router.use(announcementsRouter);
router.use(auditRouter);
router.use(backupsRouter);
router.use(settingsRouter);
router.use(systemRouter);
router.use(crashRouter);
router.use(activityRouter);
router.use(recycleRouter);

export default router;
